import { createSlice } from "@reduxjs/toolkit";

const initialExpenses = [
  {
    id: 1,
    subject: "Groceries",
    merchant: "Supermarket",
    amount: 50.75,
    date: "2024-01-01",
    category: "Food",
  },
  {
    id: 2,
    subject: "Gas",
    merchant: "Gas Station",
    amount: 40.0,
    date: "2024-01-02",
    category: "Transportation",
  },
  {
    id: 3,
    subject: "Electric Bill",
    merchant: "Utility Company",
    amount: 120.5,
    date: "2024-01-03",
    category: "Housing",
  },
  {
    id: 4,
    subject: "Movie Tickets",
    merchant: "Cinema",
    amount: 30.0,
    date: "2024-01-04",
    category: "Entertainment",
  },
  {
    id: 5,
    subject: "Coffee",
    merchant: "Cafe",
    amount: 15.0,
    date: "2024-01-05",
    category: "Food",
  },
  {
    id: 6,
    subject: "Rent",
    merchant: "Landlord",
    amount: 1500.0,
    date: "2024-01-06",
    category: "Housing",
  },
  {
    id: 7,
    subject: "Internet Bill",
    merchant: "ISP",
    amount: 60.0,
    date: "2024-01-07",
    category: "Housing",
  },
  {
    id: 8,
    subject: "Lunch",
    merchant: "Restaurant",
    amount: 25.0,
    date: "2024-01-08",
    category: "Food",
  },
  {
    id: 9,
    subject: "Gym Membership",
    merchant: "Gym",
    amount: 50.0,
    date: "2024-01-09",
    category: "Health",
  },
  {
    id: 10,
    subject: "Car Insurance",
    merchant: "Insurance Company",
    amount: 120.0,
    date: "2024-01-10",
    category: "Transportation",
  },
  {
    id: 11,
    subject: "Dinner",
    merchant: "Restaurant",
    amount: 40.0,
    date: "2024-01-11",
    category: "Food",
  },
  {
    id: 12,
    subject: "Phone Bill",
    merchant: "Phone Company",
    amount: 80.0,
    date: "2024-01-12",
    category: "Communication",
  },
  {
    id: 13,
    subject: "Clothing",
    merchant: "Department Store",
    amount: 100.0,
    date: "2024-01-13",
    category: "Shopping",
  },
  {
    id: 14,
    subject: "Travel",
    merchant: "Airline",
    amount: 500.0,
    date: "2024-01-14",
    category: "Travel",
  },
  {
    id: 15,
    subject: "Subscription",
    merchant: "Streaming Service",
    amount: 15.0,
    date: "2024-01-15",
    category: "Entertainment",
  },
  {
    id: 16,
    subject: "Pet Food",
    merchant: "Pet Store",
    amount: 30.0,
    date: "2024-01-16",
    category: "Pets",
  },
  {
    id: 17,
    subject: "Home Decor",
    merchant: "Home Goods",
    amount: 75.0,
    date: "2024-01-17",
    category: "Housing",
  },
  {
    id: 18,
    subject: "Gift",
    merchant: "Gift Shop",
    amount: 50.0,
    date: "2024-01-18",
    category: "Gifts",
  },
  {
    id: 19,
    subject: "Furniture",
    merchant: "Furniture Store",
    amount: 200.0,
    date: "2024-01-19",
    category: "Housing",
  },
  {
    id: 20,
    subject: "Appliance Repair",
    merchant: "Repair Service",
    amount: 100.0,
    date: "2024-01-20",
    category: "Housing",
  },
  {
    id: 21,
    subject: "Car Maintenance",
    merchant: "Mechanic",
    amount: 200.0,
    date: "2024-01-21",
    category: "Transportation",
  },
  {
    id: 22,
    subject: "Books",
    merchant: "Bookstore",
    amount: 50.0,
    date: "2024-01-22",
    category: "Education",
  },
  {
    id: 23,
    subject: "Medical Bill",
    merchant: "Medical Center",
    amount: 200.0,
    date: "2024-01-23",
    category: "Health",
  },
  {
    id: 24,
    subject: "Cable Bill",
    merchant: "Cable Company",
    amount: 100.0,
    date: "2024-01-24",
    category: "Entertainment",
  },
  {
    id: 25,
    subject: "Gasoline",
    merchant: "Gas Station",
    amount: 40.0,
    date: "2024-01-25",
    category: "Transportation",
  },
  {
    id: 26,
    subject: "Coffee",
    merchant: "Cafe",
    amount: 15.0,
    date: "2024-01-26",
    category: "Food",
  },
  {
    id: 27,
    subject: "Gym Membership",
    merchant: "Gym",
    amount: 50.0,
    date: "2024-01-27",
    category: "Health",
  },
  {
    id: 28,
    subject: "Lunch",
    merchant: "Restaurant",
    amount: 25.0,
    date: "2024-01-28",
    category: "Food",
  },
  {
    id: 29,
    subject: "Dinner",
    merchant: "Restaurant",
    amount: 40.0,
    date: "2024-01-29",
    category: "Food",
  },
  {
    id: 30,
    subject: "Phone Bill",
    merchant: "Phone Company",
    amount: 80.0,
    date: "2024-01-30",
    category: "Communication",
  },
  {
    id: 31,
    subject: "Subscription",
    merchant: "Streaming Service",
    amount: 15.0,
    date: "2024-01-31",
    category: "Entertainment",
  },
  {
    id: 32,
    subject: "Pet Food",
    merchant: "Pet Store",
    amount: 30.0,
    date: "2024-02-01",
    category: "Pets",
  },
  {
    id: 33,
    subject: "Gift",
    merchant: "Gift Shop",
    amount: 50.0,
    date: "2024-02-02",
    category: "Gifts",
  },
  {
    id: 34,
    subject: "Clothing",
    merchant: "Department Store",
    amount: 100.0,
    date: "2024-02-03",
    category: "Shopping",
  },
  {
    id: 35,
    subject: "Travel",
    merchant: "Airline",
    amount: 500.0,
    date: "2024-02-04",
    category: "Travel",
  },
  {
    id: 36,
    subject: "Internet Bill",
    merchant: "ISP",
    amount: 60.0,
    date: "2024-02-05",
    category: "Housing",
  },
  {
    id: 37,
    subject: "Groceries",
    merchant: "Supermarket",
    amount: 50.75,
    date: "2024-02-06",
    category: "Food",
  },
  {
    id: 38,
    subject: "Electric Bill",
    merchant: "Utility Company",
    amount: 120.5,
    date: "2024-02-07",
    category: "Housing",
  },
  {
    id: 39,
    subject: "Car Insurance",
    merchant: "Insurance Company",
    amount: 120.0,
    date: "2024-02-08",
    category: "Transportation",
  },
  {
    id: 40,
    subject: "Home Decor",
    merchant: "Home Goods",
    amount: 75.0,
    date: "2024-02-09",
    category: "Housing",
  },
];

const initialIncomes = [
  {
    id: 1,
    subject: "Freelance Web Design",
    category: "Salary",
    date: "2024-07-01",
    note: "Completed website for client X",
    amount: 1500.0,
  },
  {
    id: 2,
    subject: "Part-time Tutoring",
    category: "Others",
    date: "2024-07-05",
    note: "Math tutoring session",
    amount: 200.0,
  },
  {
    id: 3,
    subject: "Consulting Services",
    category: "Others",
    date: "2024-07-10",
    note: "Project management consultation",
    amount: 800.0,
  },
  {
    id: 4,
    subject: "Affiliate Marketing",
    category: "Others",
    date: "2024-07-15",
    note: "Commission from sales",
    amount: 120.0,
  },
  {
    id: 5,
    subject: "Rental Income",
    category: "Bank",
    date: "2024-07-20",
    note: "Monthly rent from apartment",
    amount: 1200.0,
  },
  {
    id: 6,
    subject: "Book Royalties",
    category: "Others",
    date: "2024-07-25",
    note: "Royalties from book sales",
    amount: 450.0,
  },
  {
    id: 7,
    subject: "Online Course Sales",
    category: "Others",
    date: "2024-07-30",
    note: "Income from online course",
    amount: 650.0,
  },
  {
    id: 8,
    subject: "Stock Dividends",
    category: "Stock Market",
    date: "2024-08-01",
    note: "Quarterly stock dividends",
    amount: 300.0,
  },
  {
    id: 9,
    subject: "Consulting Project",
    category: "Others",
    date: "2024-08-05",
    note: "IT consulting for company Y",
    amount: 1000.0,
  },
  {
    id: 10,
    subject: "Webinar Hosting",
    category: "Others",
    date: "2024-08-10",
    note: "Hosted a tech webinar",
    amount: 500.0,
  },
  {
    id: 11,
    subject: "Freelance Writing",
    category: "Others",
    date: "2024-08-15",
    note: "Articles for online magazine",
    amount: 300.0,
  },
  {
    id: 12,
    subject: "E-book Sales",
    category: "Others",
    date: "2024-08-20",
    note: "Sales of e-book",
    amount: 250.0,
  },
  {
    id: 13,
    subject: "Subscription Service",
    category: "Others",
    date: "2024-08-25",
    note: "Monthly subscription fee",
    amount: 150.0,
  },
  {
    id: 14,
    subject: "Software License",
    category: "Others",
    date: "2024-08-30",
    note: "License fee for software",
    amount: 700.0,
  },
  {
    id: 15,
    subject: "Consulting Retainer",
    category: "Others",
    date: "2024-09-01",
    note: "Monthly retainer for consulting",
    amount: 1200.0,
  },
  {
    id: 16,
    subject: "Freelance Graphic Design",
    category: "Salary",
    date: "2024-09-05",
    note: "Design work for client Z",
    amount: 800.0,
  },
  {
    id: 17,
    subject: "Stock Trading",
    category: "Stock Market",
    date: "2024-09-10",
    note: "Profit from stock trading",
    amount: 400.0,
  },
  {
    id: 18,
    subject: "Rental Property Income",
    category: "Bank",
    date: "2024-09-15",
    note: "Monthly rent from property Y",
    amount: 1000.0,
  },
  {
    id: 19,
    subject: "Affiliate Income",
    category: "Others",
    date: "2024-09-20",
    note: "Affiliate program earnings",
    amount: 250.0,
  },
  {
    id: 20,
    subject: "Online Course Fees",
    category: "Others",
    date: "2024-09-25",
    note: "Fees from online course",
    amount: 350.0,
  },
  {
    id: 21,
    subject: "Consulting Fee",
    category: "Others",
    date: "2024-10-01",
    note: "Fee for consulting services",
    amount: 600.0,
  },
  {
    id: 22,
    subject: "Book Sales",
    category: "Others",
    date: "2024-10-05",
    note: "Sales of published book",
    amount: 550.0,
  },
  {
    id: 23,
    subject: "Freelance Coding",
    category: "Salary",
    date: "2024-10-10",
    note: "Coding for client B",
    amount: 1200.0,
  },
  {
    id: 24,
    subject: "Stock Market Returns",
    category: "Stock Market",
    date: "2024-10-15",
    note: "Returns from stock investments",
    amount: 700.0,
  },
  {
    id: 25,
    subject: "Consulting Engagement",
    category: "Others",
    date: "2024-10-20",
    note: "Consulting for startup",
    amount: 900.0,
  },
  {
    id: 26,
    subject: "Rental Lease",
    category: "Bank",
    date: "2024-10-25",
    note: "Lease income from property X",
    amount: 1100.0,
  },
  {
    id: 27,
    subject: "Freelance Marketing",
    category: "Salary",
    date: "2024-11-01",
    note: "Marketing campaign for client",
    amount: 950.0,
  },
  {
    id: 28,
    subject: "Stock Profits",
    category: "Stock Market",
    date: "2024-11-05",
    note: "Profit from stock sales",
    amount: 400.0,
  },
  {
    id: 29,
    subject: "Affiliate Commissions",
    category: "Others",
    date: "2024-11-10",
    note: "Commissions from affiliate sales",
    amount: 300.0,
  },
  {
    id: 30,
    subject: "Consulting Retainer Fee",
    category: "Others",
    date: "2024-11-15",
    note: "Retainer fee for consulting",
    amount: 1200.0,
  },
  {
    id: 31,
    subject: "E-book Royalties",
    category: "Others",
    date: "2024-11-20",
    note: "Royalties from e-book sales",
    amount: 450.0,
  },
  {
    id: 32,
    subject: "Webinar Income",
    category: "Others",
    date: "2024-11-25",
    note: "Income from webinar registration",
    amount: 350.0,
  },
  {
    id: 33,
    subject: "Freelance Editing",
    category: "Salary",
    date: "2024-12-01",
    note: "Editing services for client",
    amount: 700.0,
  },
  {
    id: 34,
    subject: "Stock Earnings",
    category: "Stock Market",
    date: "2024-12-05",
    note: "Earnings from stock investments",
    amount: 500.0,
  },
  {
    id: 35,
    subject: "Rental Property Rent",
    category: "Bank",
    date: "2024-12-10",
    note: "Rent income from property",
    amount: 1000.0,
  },
  {
    id: 36,
    subject: "Freelance Writing Project",
    category: "Salary",
    date: "2024-12-15",
    note: "Writing project for client",
    amount: 800.0,
  },
  {
    id: 37,
    subject: "Affiliate Program",
    category: "Others",
    date: "2024-12-20",
    note: "Income from affiliate program",
    amount: 200.0,
  },
  {
    id: 38,
    subject: "Consulting Income",
    category: "Others",
    date: "2024-12-25",
    note: "Income from consulting services",
    amount: 600.0,
  },
  {
    id: 39,
    subject: "Book Licensing",
    category: "Others",
    date: "2024-12-30",
    note: "License fee for book",
    amount: 700.0,
  },
  {
    id: 40,
    subject: "Freelance Design",
    category: "Salary",
    date: "2025-01-01",
    note: "Design work for client A",
    amount: 900.0,
  },
];

const expenseSlice = createSlice({
  name: "expense",
  initialState: {
    income: 0,
    expense: 0,
    balance: 0,
    transaction: 0,
    expensesList: [],
    incomeList: [],
  },
  reducers: {
    addExpense: (state, action) => {
      state.expensesList.push(action.payload);
      state.expense += action.payload.amount;
      state.balance -= action.payload.amount;
      state.transaction += 1;
    },
    addIncome: (state, action) => {
      state.incomeList.push(action.payload);
      state.income += action.payload.amount;
      state.balance += action.payload.amount;
      state.transaction += 1;
      console.log(action.payload);
    },
    updateIncome: (state, action) => {
      const { id, subject, amount, date, category, note } = action.payload;
      const index = state.incomeList.findIndex((income) => income.id === id);
      if (index !== -1) {
        state.incomeList[index] = { id, subject, amount, date, category, note };
      }
    },

    deleteIncome: (state, action) => {
      console.log(action.payload, "findid for deleted");
      state.incomeList = state.incomeList.filter(
        (income) => income.id !== action.payload
      );
    },

    updateExpense: (state, action) => {
      const { id, subject, merchant, amount, date, category } = action.payload;
      const index = state.expensesList.findIndex(
        (expense) => expense.id === id
      );
      if (index !== -1) {
        state.expensesList[index] = {
          id,
          subject,
          merchant,
          amount,
          date,
          category,
        };
      }
    },

    deleteExpense: (state, action) => {
      console.log(action.payload, "findid for deleted");
      state.expensesList = state.expensesList.filter(
        (expense) => expense.id !== action.payload
      );
    },
  },
});

export const {
  addExpense,
  addIncome,
  updateIncome,
  updateExpense,
  deleteExpense,
  deleteIncome,
} = expenseSlice.actions;
export default expenseSlice.reducer;
